name: Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/efrecon/nighthawk
